title: Aulas Pedro Kroger
email: kroger@ufba.br
description: Aulas de Pedro Kroger
url: "https://pkroger.com"

timezone: "America/Bahia"

exclude: [Makefile]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "aulas"
      type: "pages"
    values:
      layout: "aula"
      permalink: /:basename/
